### ISSUE TITLE
UMF: OpenConfig YANG support for Physical Interfaces

### ISSUE THREAD

**Issue by jeff-yin** [sonic-net/sonic-mgmt-common#131]
Add OpenConfig YANG model support for physical interfaces. Establish the translation/mapping from SONiC YANG to OpenConfig YANG, declare what is not/supported and any SONiC-specific deviations. 

Code PRs:
| Repo              | PR title          | State             |
| ----------------- | ----------------- | ----------------- |
| SONiC | [Adding HLD for OC Yang interfaces.](https://github.com/sonic-net/SONiC/pull/1628)    | ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-net/SONiC/pull/1628) |
|  sonic-mgmt-common     | [Adding support for OC YANG interfaces](https://github.com/sonic-net/sonic-mgmt-common/pull/125)   |   ![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/sonic-net/sonic-net/sonic-mgmt-common/pull/12) |

**Comment by zhangyanzhao** [comment]
all PRs are merged, mark this as  done for 202405 release
